kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-filestore-storageclass-reader-resizer-binding
subjects:
  - kind: ServiceAccount
    name: gcp-filestore-csi-driver-controller-sa
    namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: openshift-csi-resizer-storageclass-reader-role
  apiGroup: rbac.authorization.k8s.io
